import { RecommendationCandidate } from '../climate/calculations';

export const ACTION_CATALOG: RecommendationCandidate[] = [
  {
    id: 'sauna-night-shift',
    category: 'sauna_optimizer',
    action: 'Schedule electric sauna session to off-peak night wind hours (after 21:00)',
    title: 'Nordic Sauna Smart Shift',
    titleFi: 'Älykäs saunavuoro (Yösähkö & Tuulivoima)',
    description: 'Heating the 6.8 kW kiuas when spot prices drop to 2.4 c/kWh and clean wind power peaks saves money and avoids peak-hour fossil fuel generation.',
    descriptionFi: 'Lämmitä 6.8 kW kiuas klo 21:00 jälkeen, kun pörssisähkö on 2.4 c/kWh ja kantaverkossa on runsaasti tuulivoimaa.',
    estimatedCO2Kg: 1.25,
    estimatedSavingEur: 1.55,
    energyKWh: 10.2,
    effort: 'low',
    convenienceImpact: 'minimal',
    requiredFlexibility: 'time_shift',
    confidence: 0.95,
    excludedByConstraints: ['no_sauna'],
    requiredContext: ['has_sauna'],
  },
  {
    id: 'heating-temp-reduction',
    category: 'heating_optimization',
    action: 'Lower indoor heating by 1°C (22°C -> 21°C) and wear cozy Nordic wool socks',
    title: 'Living Room Comfort Tune (1°C Lower)',
    titleFi: 'Huonelämmön optimointi (-1°C ja villasukat)',
    description: 'Reducing room temperature by 1°C saves ~5% of annual heating energy in Espoo without compromising living comfort.',
    descriptionFi: 'Huonelämpötilan lasku yhdellä asteella säästää n. 5% lämmitysenergiasta ja parantaa sisäilman raikkautta.',
    estimatedCO2Kg: 2.70,
    estimatedSavingEur: 0.85,
    effort: 'low',
    convenienceImpact: 'minimal',
    requiredFlexibility: 'habit_change',
    confidence: 0.92,
    excludedByConstraints: ['no_temperature_reduction'],
  },
  {
    id: 'pikaratikka-15-commute',
    category: 'transport_hsl',
    action: 'Take HSL Pikaratikka 15 light rail or Länsimetro for your daily Espoo commute',
    title: 'Zero-Emission Rail Commute (Pikaratikka 15)',
    titleFi: 'Nollapäästöinen työmatka (Pikaratikka 15 & Länsimetro)',
    description: 'Replacing a 10 km single-occupancy car drive with 100% renewable electric rail eliminates ~1.4 kg CO2 per trip and saves fuel/parking costs.',
    descriptionFi: 'Korvaa 10 km autoilu uusiutuvalla sähköllä kulkevalla pikaratikalla tai metrolla. Säästää polttoainetta ja pysäköintimaksuja.',
    estimatedCO2Kg: 1.42,
    estimatedSavingEur: 2.70,
    effort: 'medium',
    convenienceImpact: 'moderate',
    requiredFlexibility: 'habit_change',
    confidence: 0.94,
    excludedByConstraints: ['mobility_limitations', 'no_transit_route'],
  },
  {
    id: 'bio-and-plastic-sorting',
    category: 'waste_circular',
    action: 'Sort all food waste into HSY bio-waste and separate clean plastic packagings',
    title: '100% Circular Bio & Plastic Sorting',
    titleFi: '100% Bio- ja muovipakkausten lajittelu',
    description: 'Directing food waste to biogas generation at Ämmässuo and plastics to recycled polymer granulate saves fossil feedstocks.',
    descriptionFi: 'Lajittele ruokajätteet Ämmässuon biokaasutuotantoon ja muovit CIRCO-kierrätysmuoviksi sekajätteen sijaan.',
    estimatedCO2Kg: 0.85,
    estimatedSavingEur: 0.30,
    effort: 'low',
    convenienceImpact: 'minimal',
    requiredFlexibility: 'habit_change',
    confidence: 0.96,
  },
  {
    id: 'ev-smart-charging',
    category: 'ev_smart_charge',
    action: 'Plug in EV but delay charging to automated night window (01:00 - 05:00)',
    title: 'EV Dynamic Wind Charging',
    titleFi: 'Sähköauton älykäs yölataus',
    description: 'Charging 40 kWh during midnight valley prices (2.1 c/kWh) maximizes clean nuclear and wind utilization.',
    descriptionFi: 'Lataa sähköauto yön edullisimpina tuulitunteina (01:00 - 05:00) minimoiden latauskulut ja verkkokuorman.',
    estimatedCO2Kg: 3.10,
    estimatedSavingEur: 4.80,
    energyKWh: 40.0,
    effort: 'low',
    convenienceImpact: 'minimal',
    requiredFlexibility: 'time_shift',
    confidence: 0.98,
    excludedByConstraints: ['no_ev', 'no_car'],
    requiredContext: ['has_ev'],
  },
];
