/**
 * Authoritative Nordic Emissions and Energy Constants
 * Used strictly by the Deterministic Engine for calculations.
 */
export const NORDIC_EMISSION_FACTORS = {
  // Grid electricity emissions (g CO2e / kWh)
  GRID_FINLAND_AVERAGE: 45,
  GRID_FINLAND_PEAK_FOSSIL: 140,
  GRID_FINLAND_WIND_CLEAN: 18,

  // District heating Fortum Espoo (g CO2e / kWh)
  DISTRICT_HEAT_ESPOO_2026: 68,
  DISTRICT_HEAT_ESPOO_2030_TARGET: 12,

  // Direct heating types
  DIRECT_ELECTRIC: 45,
  OIL_HEATING: 268,
  WOOD_HEATING_NET: 25,

  // Transport emissions per passenger-km (g CO2e / passenger-km)
  TRANSPORT_ICE_CAR_AVERAGE: 142,
  TRANSPORT_EV_FINNISH_GRID: 19,
  TRANSPORT_PHEV_AVERAGE: 65,
  TRANSPORT_HSL_METRO_RAIL: 0,
  TRANSPORT_HSL_PIKARATIKKA_15: 0,
  TRANSPORT_HSL_ELECTRIC_BUS: 8,
  TRANSPORT_CYCLING_WALKING: 0,

  // Waste diversion savings vs mixed waste incineration (g CO2e saved / kg material recycled)
  RECYCLING_PLASTIC_SAVING_PER_KG: 1450,
  RECYCLING_CARDBOARD_SAVING_PER_KG: 850,
  RECYCLING_BIOWASTE_BIOGAS_PER_KG: 420,
  RECYCLING_METALS_SAVING_PER_KG: 2100,
  RECYCLING_GLASS_SAVING_PER_KG: 380,
  RECYCLING_TEXTILES_PER_KG: 3200,

  // Food & Grocery approximate category emissions (kg CO2e / kg food - Luke & SYKE Finland averages)
  FOOD_CHICKEN_PER_KG: 3.8,
  FOOD_BEEF_PER_KG: 28.0,
  FOOD_PORK_PER_KG: 5.5,
  FOOD_PLANT_PROTEIN_TOFU_OATS_PER_KG: 0.9,
  FOOD_DAIRY_MILK_PER_LITER: 1.2,
  FOOD_OAT_MILK_PER_LITER: 0.3,
  FOOD_RICE_PER_KG: 2.7,
  FOOD_POTATOES_ROOTS_PER_KG: 0.2,
  FOOD_IMPORTED_BANANAS_PER_KG: 0.8,
  FOOD_LOCAL_APPLES_BERRIES_PER_KG: 0.3,

  // Sauna specs (standard Finnish household)
  KIUAS_DEFAULT_KW: 6.8,
  KIUAS_HEATING_HOURS: 1.5,
};

export const NORDIC_PRICING_BENCHMARKS = {
  SPOT_EVENING_PEAK_CENTS: 17.5,
  SPOT_OFF_PEAK_NIGHT_CENTS: 2.4,
  SPOT_DAY_AVERAGE_CENTS: 5.8,

  HSL_AB_SINGLE_TICKET_EUR: 3.10,
  CAR_FUEL_AND_MAINTENANCE_PER_KM_EUR: 0.28,
  CAR_PARKING_HOURLY_ESPOO_EUR: 2.00,

  // Food item benchmarks (EUR per unit)
  FOOD_PRICE_CHICKEN_500G: 4.50,
  FOOD_PRICE_PLANT_PROTEIN_500G: 3.95,
  FOOD_PRICE_DAIRY_MILK_1L: 1.15,
  FOOD_PRICE_OAT_MILK_1L: 1.85,
  FOOD_PRICE_RICE_500G: 1.20,
  FOOD_PRICE_POTATOES_500G: 0.60,
  FOOD_PRICE_BANANAS_1KG: 1.80,
};
